# Generated by Django 4.0 on 2022-01-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='height',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
