# Generated by Django 4.0 on 2022-01-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='segments',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='name',
        ),
        migrations.AddField(
            model_name='customsegment',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='definedsegment',
            name='name',
            field=models.CharField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
