# Generated by Django 4.0 on 2022-01-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
