# Generated by Django 4.0 on 2022-01-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_point_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.user')),
                ('birth_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_user', to='mysite.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('mysite.user',),
        ),
    ]
